/**
 * optimization_parity.js — Verify JS knapsack result matches Python MILP to 2 decimals.
 *
 * Run from the repo root:
 *   node scripts/optimization_parity.js
 *
 * Reads dashboard/public/data/dashboard.json (regenerated by run_pipeline.py).
 *
 * With the shipped template (all TBD), there are no ready measures and parity
 * trivially holds (both = 0). When measures are filled in, this script must
 * confirm the JS knapsack DP gives the same tCO₂e as Python MILP for 2–3
 * fixed budgets stored in the JSON budget_sweep.
 *
 * Exit 0 = parity OK, exit 1 = mismatch or data error.
 */

import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { join, dirname } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const jsonPath = join(__dirname, '..', 'dashboard', 'public', 'data', 'dashboard.json')
const data = JSON.parse(readFileSync(jsonPath, 'utf8'))

const opt = data.optimization
const TOLERANCE = 0.01

// ── JS knapsack (mirrors Optimization.jsx) ────────────────────────────────────
const STEP_INR = 1_000

function knapsack(measures, budget, caps) {
  const B = Math.floor(budget / STEP_INR)
  const n = measures.length
  if (n === 0 || B <= 0) return { selected: {}, tco2e: 0, capex: 0 }

  let dp = new Array(B + 1).fill(0)
  const choice = Array.from({ length: n }, () => new Int8Array(B + 1))

  for (let i = 0; i < n; i++) {
    const m = measures[i]
    const cost = Math.ceil(m.capex_per_unit / STEP_INR)
    const val = m.tco2e_per_unit
    const maxU = Math.min(m.max_units, Math.floor(B / Math.max(cost, 1)))
    const next = new Float64Array(dp)

    for (let u = 1; u <= maxU; u++) {
      for (let j = B; j >= cost * u; j--) {
        const v = dp[j - cost * u] + val * u
        if (v > next[j]) { next[j] = v; choice[i][j] = u }
      }
    }
    dp = Array.from(next)
  }

  const units = {}
  let j = B
  for (let i = n - 1; i >= 0; i--) {
    const u = choice[i][j]
    if (u > 0) {
      units[measures[i].id] = u
      j -= Math.ceil(measures[i].capex_per_unit / STEP_INR) * u
    }
  }

  // Exclusive groups
  const groups = {}
  for (const m of measures) {
    if (m.exclusive_group && units[m.id] > 0) {
      groups[m.exclusive_group] = groups[m.exclusive_group] ?? []
      groups[m.exclusive_group].push({ id: m.id, tco2e: m.tco2e_per_unit * units[m.id] })
    }
  }
  for (const eg of Object.keys(groups)) {
    const members = groups[eg].sort((a, b) => b.tco2e - a.tco2e)
    for (let k = 1; k < members.length; k++) delete units[members[k].id]
  }

  // Cap enforcement (post-DP)
  let changed = true
  while (changed) {
    changed = false
    const elecUsed = measures.reduce((s, m) => s + (units[m.id] ?? 0) * m.kwh_per_unit, 0)
    const dieselUsed = measures.reduce((s, m) => s + (units[m.id] ?? 0) * m.litres_per_unit, 0)
    const acUsed = measures.filter(m => m.cap_basis === 'ac_end_use')
      .reduce((s, m) => s + (units[m.id] ?? 0) * m.kwh_per_unit, 0)

    const viol = []
    if (caps.total_electricity != null && elecUsed > caps.total_electricity + 1) viol.push('elec')
    if (caps.total_diesel != null && dieselUsed > caps.total_diesel + 1) viol.push('diesel')
    if (caps.ac_end_use != null && acUsed > caps.ac_end_use + 1) viol.push('ac')

    if (viol.length > 0) {
      const cands = measures.filter(m => units[m.id] > 0)
      if (!cands.length) break
      cands.sort((a, b) =>
        (a.tco2e_per_unit / a.capex_per_unit) - (b.tco2e_per_unit / b.capex_per_unit))
      delete units[cands[0].id]
      changed = true
    }
  }

  const tco2e = measures.reduce((s, m) => s + (units[m.id] ?? 0) * m.tco2e_per_unit, 0)
  const capex = measures.reduce((s, m) => s + (units[m.id] ?? 0) * m.capex_per_unit, 0)
  return { selected: units, tco2e, capex }
}

// ── Check ─────────────────────────────────────────────────────────────────────
const readyMeasures = (opt.measures ?? [])
  .filter(m => m.status === 'ready' && m.impact && m.impact.tco2e_saved_per_unit > 0)
  .map(m => ({
    id: m.id,
    label: m.label,
    capex_per_unit: m.impact.capex_per_unit,
    tco2e_per_unit: m.impact.tco2e_saved_per_unit,
    kwh_per_unit: m.impact.kwh_saved_per_unit,
    litres_per_unit: m.impact.litres_saved_per_unit,
    max_units: m.max_units ?? 1,
    exclusive_group: m.exclusive_group ?? null,
    cap_basis: m.cap_basis ?? null,
  }))

const caps = {
  total_electricity: data.kpis?.electricity_kwh ?? null,
  total_diesel: data.kpis?.diesel_litres ?? null,
  ac_end_use: 233054,
}

const sweep = opt.budget_sweep ?? []

if (readyMeasures.length === 0) {
  console.log('Parity check: no ready measures — both Python and JS return 0 tCO₂e.')
  console.log('PASS (trivial): all measures are TBD. Fill optimization_measures.csv and re-run.')
  process.exit(0)
}

let allPass = true
const checkBudgets = sweep.length > 0
  ? sweep.slice(0, 3).map(r => r.budget_inr)
  : [500_000, 1_000_000, 2_000_000]

console.log(`Parity check: ${readyMeasures.length} ready measures, ${checkBudgets.length} budget levels`)

for (const b of checkBudgets) {
  const jsResult = knapsack(readyMeasures, b, caps)
  // Python result from sweep
  const pyRow = sweep.find(r => r.budget_inr === b)
  const pyT = pyRow ? pyRow.optimal_tco2e_saved : null

  if (pyT === null) {
    console.log(`  Budget ₹${b.toLocaleString('en-IN')}: JS = ${jsResult.tco2e.toFixed(4)}, Python = N/A (no sweep data)`)
    continue
  }

  const diff = Math.abs(jsResult.tco2e - pyT)
  const ok = diff <= TOLERANCE
  if (!ok) allPass = false

  console.log(
    `  Budget ₹${b.toLocaleString('en-IN')}: ` +
    `JS = ${jsResult.tco2e.toFixed(4)}, Python = ${pyT.toFixed(4)}, ` +
    `diff = ${diff.toFixed(6)} → ${ok ? 'PASS ✅' : 'FAIL ❌'}`
  )
}

if (allPass) {
  console.log('\nPASS: JS knapsack and Python MILP agree within 0.01 tCO₂e at all checked budgets.')
  process.exit(0)
} else {
  console.error('\nFAIL: JS and Python results differ beyond tolerance. Check cap enforcement or rounding.')
  process.exit(1)
}
