/**
 * parity_check.js — Verify JS simulation result matches Python to 2 decimals.
 *
 * Run from the repo root:
 *   node scripts/parity_check.js
 *
 * Reads dashboard/public/data/dashboard.json (regenerated by run_pipeline.py).
 * Applies a fixed scenario: electricity −10%, diesel −5%, solar 5000 kWh/month.
 * Compares the JS result to the Python pre-computed result stored in the JSON.
 *
 * Exit code 0 = parity OK, 1 = mismatch (> 0.01 tCO2e on annual total).
 */

import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { join, dirname } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const jsonPath = join(__dirname, '..', 'dashboard', 'public', 'data', 'dashboard.json')
const data = JSON.parse(readFileSync(jsonPath, 'utf8'))

const sim = data.simulation
const factors = sim.factors_used
const ef = {}
for (const f of factors) ef[f.name] = f

// ── JS accounting formula (same as Simulation.jsx) ────────────────────────────
function runJS(baselineMonthly, elecPct, dselPct, solarKwh) {
  const EF_ELEC = ef.electricity.factor
  const EF_DSEL = ef.diesel.factor
  let scope2 = 0, scope1 = 0
  for (const row of baselineMonthly) {
    const scenElec = Math.max(0, row.base_electricity_kwh * (1 + elecPct / 100) - solarKwh)
    const scenDiesel = Math.max(0, row.base_diesel_litres * (1 + dselPct / 100))
    scope2 += scenElec * EF_ELEC / 1000
    scope1 += scenDiesel * EF_DSEL / 1000
  }
  return +((scope2 + scope1).toFixed(4))
}

// ── Python reference: use the preset "led_retrofit" (electricity −15%) ────────
const ledPreset = sim.presets.find(p => p.id === 'led_retrofit')
if (!ledPreset) { console.error('ERROR: led_retrofit preset not found in JSON'); process.exit(1) }

const pyAnnual = ledPreset.annual.scenario_total_tco2e
const jsAnnual = runJS(sim.baseline_monthly, -15, 0, 0)

const diff = Math.abs(pyAnnual - jsAnnual)
const TOLERANCE = 0.01

console.log('Parity check: LED retrofit −15% electricity')
console.log(`  Python result: ${pyAnnual} tCO₂e/yr`)
console.log(`  JS result:     ${jsAnnual} tCO₂e/yr`)
console.log(`  Difference:    ${diff.toFixed(6)} tCO₂e (tolerance: ${TOLERANCE})`)

if (diff > TOLERANCE) {
  console.error(`FAIL: JS and Python results differ by ${diff.toFixed(6)} > ${TOLERANCE}`)
  process.exit(1)
} else {
  console.log('PASS: JS and Python results agree to 2 decimal places.')
  process.exit(0)
}
